const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'), staged=root,ts=require(root+'/node_modules/typescript');
let b,user='owner',role='USER',operations=false,calls=[],mails=[],mailFails=false,mailErrors=[];
const tx={$queryRaw:async()=>[],booking:{findUniqueOrThrow:async()=>structuredClone(b),update:async({data})=>Object.assign(b,data)},user:{findUnique:async()=>({role,email:'renter@example.test'})},settlementOperation:{findFirst:async()=>operations?{id:'op'}:null}};
let queue=Promise.resolve();
const prisma={...tx,$transaction:fn=>{const run=queue.then(async()=>{const before=structuredClone(b);try{return await fn(tx);}catch(e){b=before;throw e;}});queue=run.catch(()=>{});return run;}};
const cache=new Map();
function load(f){if(cache.has(f))return cache.get(f);const file=fs.existsSync(path.join(staged,f))?path.join(staged,f):root+'/'+f;const out=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};function req(id){if(id==='@/app/lib/logisticsIssueEmail')return {notifyLogisticsIssue:async()=>{}};if(id==='@/app/lib/mailer')return {sendMail:async mail=>{assert.equal(b.depositClaim.status,'PENDING');if(mailFails)throw Error('Mock SMTP failure');mails.push(mail);}};if(id==='@/app/lib/prisma')return {prisma};if(id==='@prisma/client')return {Prisma:{DbNull:null}};if(id==='next-auth')return {getServerSession:async()=>user?{user:{id:user}}:null};if(id==='@/auth.config')return {authConfig:{}};if(id==='next/cache')return {revalidatePath:()=>{}};if(id==='stripe')return {};if(id==='node:crypto')return require(id);if(id==='./depositActions')return Object.fromEntries(['releaseDepositAction','partialReleaseDepositAction','retainDepositAction','retrySettlementAction'].map(k=>[k,async form=>calls.push([k,Object.fromEntries(form)])]));if(id.startsWith('@/'))return load(id.slice(2)+'.ts');throw Error(id);}vm.runInNewContext(out,{exports,require:req,Date,console:{...console,error:(...args)=>mailErrors.push(args)},FormData,process:{env:{NEXT_PUBLIC_APP_URL:'https://example.test'}}});cache.set(f,exports);return exports;}
tx.booking.updateMany=async({where,data})=>{const ok=Object.entries(where).every(([key,value])=>value&&typeof value==='object'?('in' in value?value.in.includes(b[key]):'not' in value?b[key]!==value.not:false):b[key]===value);if(!ok)return {count:0};Object.assign(b,data);return {count:1};};
const report=load('app/bookings/[id]/_actions/reportLogisticsProblemAction.ts').reportLogisticsProblemAction;
const receipt=load('app/lib/logisticsIssue.ts');
const actions=load('app/bookings/[id]/_actions/depositClaimActions.ts'),policy=load('app/lib/depositAutoReleasePolicy.ts'),helper=load('app/lib/depositClaim.ts'),settlement=load('app/lib/settlement.ts');
const {proposeDepositClaimAction:propose,respondDepositClaimAction:respond,resolveDepositClaimBySupportAction:support,executeApprovedClaimAction:execute}=actions;
function reset(){user='owner';role='USER';operations=false;calls=[];mails=[];mailFails=false;mailErrors=[];b={id:'b',bookingNumber:10077,ownerId:'owner',renterId:'renter',status:'PAID',paymentStatus:'PAID',paidAt:new Date(),cancelledAt:null,depositStatus:'PAID',depositCents:2000,depositPaymentIntentId:'pi',depositClaim:null,settlementDecision:null,settlementCompletedAt:null,settlementLegacyReview:false,depositDecisionAt:null,depositDecisionById:null,depositRetentionReason:null,depositRetentionReasonCode:null,deliveryConfirmationStatus:'CONFIRMED',shippingStatus:'DELIVERED',returnStatus:'SHIPPED',returnConfirmationStatus:'AWAITING_CONFIRMATION',returnConfirmedAt:null,returnIssue:null,damageClaimStatus:'NONE'};}
function form(extra={}){const f=new FormData();for(const[k,v]of Object.entries({bookingId:'b',retainedAmountZl:'5.00',reasonCode:'DAMAGE',reason:'Uszkodzony rękaw',received:'yes',claimId:b.depositClaim?.id??'',response:'ACCEPT',consent:'yes',note:'Sprawdzono dowody',...extra}))f.set(k,v);return f;}
const decision=(over={})=>({kind:'partial',refundCents:1500,retainedCents:500,reason:'Uszkodzony rękaw',reasonCode:'DAMAGE',destination:'acct',paymentIntent:'pi',ownerCents:10000,...over});
let checks=0;async function rejects(fn){await assert.rejects(fn);checks++;}
(async()=>{
for(const reason of ['DAMAGED','MISSING_ITEMS','NOT_RECEIVED','OTHER']) {
 reset();const f=form({stage:'RETURN',reason,description:'Test report',received:reason==='OTHER'?'yes':'no'});await report(f);
 assert.equal(b.returnConfirmationStatus,'DISPUTED');assert.equal(b.settlementDecision,null);
 assert.equal(receipt.hasReturnReceipt(b),reason!=='NOT_RECEIVED');
 if(reason!=='NOT_RECEIVED'){assert.equal(b.returnStatus,'DELIVERED');assert.ok(b.returnDeliveredAt);await propose(form({received:'no'}));assert.equal(b.depositClaim.status,'PENDING');}
 else {assert.equal(b.returnStatus,'SHIPPED');await rejects(()=>propose(form({received:'no'})));}
 assert.equal(policy.canStartAutomaticDepositRelease(b,new Date(Date.now()+72*3600000)),false);checks++;
}
reset();await rejects(()=>report(form({stage:'RETURN',reason:'OTHER',received:'',description:'Test'})));
reset();await report(form({stage:'RETURN',reason:'OTHER',received:'no',description:'Test'}));await rejects(()=>propose(form({received:'no'})));
reset();user='renter';await rejects(()=>report(form({stage:'RETURN',reason:'DAMAGED',description:'Test'})));
reset();b.returnIssue={reason:'DAMAGED',description:'old',reportedById:'owner',reportedAt:null,resolvedAt:null,resolvedById:null};b.returnConfirmationStatus='DISPUTED';await propose(form({received:'no'}));checks++;
reset();b.returnConfirmationStatus='CONFIRMED';await propose(form({received:'no'}));checks++;
for(const extra of [{received:'no'},{retainedAmountZl:'0'},{retainedAmountZl:'21'},{retainedAmountZl:'1.001'},{retainedAmountZl:'-1'},{reasonCode:'__proto__'},{reason:''}]){reset();await rejects(()=>propose(form(extra)));assert.equal(b.depositClaim,null);}
for(const patch of [{paymentStatus:'PENDING'},{status:'CANCELLED'},{returnStatus:'PENDING'},{deliveryConfirmationStatus:'DISPUTED'},{depositStatus:'REFUNDED'},{settlementDecision:{}},{depositRefundId:'re'},{settlementLegacyReview:true},{returnConfirmedAt:new Date(Date.now()-49*3600000)}]){reset();Object.assign(b,patch);await rejects(()=>propose(form()));}
reset();user='renter';await rejects(()=>propose(form()));user=null;await rejects(()=>propose(form()));reset();operations=true;await rejects(()=>propose(form()));
reset();const attempts=await Promise.allSettled([propose(form()),propose(form())]);assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);checks++;assert.equal(mails.length,1);assert.equal(mails[0].to,'renter@example.test');assert.match(mails[0].text,/15,00/);assert.match(mails[0].text,/5,00/);assert.ok(mails[0].html.includes('https://example.test/bookings/b'));assert.equal(b.depositClaim.status,'PENDING');assert.equal(b.returnConfirmationStatus,'DISPUTED');assert.equal(calls.length,0);
await rejects(()=>settlement.lockSettlementDecision('b',decision()));await rejects(()=>settlement.lockSettlementDecision('b',decision({kind:'full',refundCents:2000,retainedCents:0,reason:null,reasonCode:null})));
await rejects(()=>respond(form()));user='renter';await rejects(()=>respond(form({consent:'no'})));await rejects(()=>respond(form({claimId:'wrong'})));await respond(form());assert.equal(b.depositClaim.status,'APPROVED');assert.equal(b.returnConfirmationStatus,'CONFIRMED');assert.equal(calls.length,0);checks++;
b.returnConfirmedAt=new Date(Date.now()-72*3600000);assert.equal(policy.canStartAutomaticDepositRelease(b),false);await rejects(()=>settlement.lockSettlementDecision('b',decision({retainedCents:600,refundCents:1400})));
await execute(form({retainedAmountZl:'20'}));assert.equal(calls[0][0],'partialReleaseDepositAction');assert.equal(calls[0][1].refundAmountZl,'15.00');checks++;
await settlement.lockSettlementDecision('b',decision());assert.equal(b.settlementDecision.source,'claim');await settlement.lockSettlementDecision('b',decision());await rejects(()=>settlement.lockSettlementDecision('b',decision({reason:'changed'})));checks++;
for(const amount of ['0','3','5']){reset();await propose(form());user='renter';await respond(form({response:'DISPUTE'}));assert.equal(b.depositClaim.status,'DISPUTED');await rejects(()=>execute(form()));await rejects(()=>support(form()));role='ADMIN';await rejects(()=>support(form()));user='staff';await rejects(()=>support(form({retainedAmountZl:'6'})));await support(form({retainedAmountZl:amount}));assert.equal(b.depositClaim.approvedRetainedCents,Number(amount)*100);await execute(form());assert.equal(calls[0][0],amount==='0'?'releaseDepositAction':'partialReleaseDepositAction');checks++;}
reset();await propose(form({retainedAmountZl:'20'}));user='renter';await respond(form());await execute(form());assert.equal(calls[0][0],'retainDepositAction');checks++;
reset();b.returnStatus='DELIVERED';b.returnConfirmationStatus='CONFIRMED';b.returnConfirmedAt=new Date();await rejects(()=>settlement.lockSettlementDecision('b',decision()));await settlement.lockSettlementDecision('b',decision({kind:'full',retainedCents:0,refundCents:2000,reason:null,reasonCode:null}));checks++;
reset();b.settlementDecision=decision();await settlement.lockSettlementDecision('b',decision());checks++;
reset();b.returnStatus='DELIVERED';b.returnConfirmationStatus='CONFIRMED';b.returnConfirmedAt=new Date(Date.now()-72*3600000);assert.equal(policy.canStartAutomaticDepositRelease(b),true);for(const status of ['PENDING','DISPUTED','APPROVED']){b.depositClaim={status};assert.equal(policy.canStartAutomaticDepositRelease(b),false);checks++;}
assert.equal(helper.parseClaimAmount('0,01'),1);assert.equal(helper.readDepositClaim({status:'APPROVED'}),null);checks+=2;
reset();await propose(form({retainedAmountZl:'10',reason:'<img src=x onerror=alert(1)>'}));assert.equal(mails.length,1);assert.match(mails[0].html,/&lt;img/);assert.ok(!mails[0].html.includes('<img'));assert.match(mails[0].text,/10,00/);checks++;
reset();await rejects(()=>propose(form({retainedAmountZl:'21'})));assert.equal(mails.length,0);checks++;
reset();mailFails=true;await propose(form());assert.equal(b.depositClaim.status,'PENDING');assert.equal(mails.length,0);assert.equal(mailErrors.length,1);assert.equal(calls.length,0);checks++;
console.log(checks+' checks passed; mocked database/payment actions, no external operations.');
})().catch(e=>{console.error(e);process.exitCode=1;});
