const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), assert = require('node:assert/strict');
const root=path.resolve(__dirname,'..'),ts=require(path.join(root,'node_modules/typescript'));
let rows=new Map(),mails=[],failTo=null,sequence=0;
const env={APP_URL:'https://staging.example.test'};
const booking={id:'b',bookingNumber:123,ownerId:'owner',renterId:'renter',owner:{id:'owner',email:'owner@example.test'},renter:{id:'renter',email:'renter@example.test'},listing:{title:'<script>Rental</script>'}};
const store={
  upsert:async({where,create})=>{if(!rows.has(where.eventKey))rows.set(where.eventKey,{id:`n${++sequence}`,createdAt:new Date(),nextAttemptAt:new Date(0),leaseUntil:null,sentAt:null,attempts:0,lastError:null,...create,incident:{bookingId:'b'}});return structuredClone(rows.get(where.eventKey));},
  findMany:async({where,take})=>Array.from(rows.values()).filter(e=>!e.sentAt&&e.nextAttemptAt<=where.nextAttemptAt.lte&&(!e.leaseUntil||e.leaseUntil<=new Date())&&(!where.incident||where.incident.bookingId===e.incident.bookingId)).slice(0,take).map(e=>structuredClone(e)),
  updateMany:async({where,data})=>{const e=Array.from(rows.values()).find(e=>e.id===where.id);if(!e||e.sentAt||where.nextAttemptAt&&e.nextAttemptAt>where.nextAttemptAt.lte||where.OR&&e.leaseUntil&&e.leaseUntil>new Date()||where.leaseUntil&&+e.leaseUntil!==+where.leaseUntil)return{count:0};for(const[k,v]of Object.entries(data)){if(k==='attempts')e[k]+=v.increment;else e[k]=v;}return{count:1};},
};
const tx={booking:{findUniqueOrThrow:async()=>structuredClone(booking)},incidentNotification:store};
const cache=new Map();
function load(file){if(cache.has(file))return cache.get(file);const exports={};function req(id){if(id==='@/app/lib/prisma')return{prisma:{incidentNotification:store}};if(id==='@/app/lib/mailer')return{sendMail:async m=>{if(failTo===m.to){failTo=null;throw Error('SMTP temporarily unavailable');}mails.push(m);}};if(id.startsWith('@/'))return load(id.slice(2)+'.ts');throw Error(id);}
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:req,Date,Intl,console:{error(){}},process:{env},encodeURIComponent});cache.set(file,exports);return exports;}
const {queueIncidentEmail:queue,sendPendingIncidentEmails:send}=load('app/lib/incidentNotification.ts');
const incident={id:'i',bookingId:'b',stage:'DELIVERY',reason:'NOT_AS_DESCRIBED',status:'AWAITING_OWNER',description:'Opis problemu <script>',resolution:null,refundCents:null,acceptedAt:null};
let checks=0;async function test(name,fn){rows=new Map();mails=[];failTo=null;sequence=0;env.APP_URL='https://staging.example.test';await fn();checks++;console.log('PASS',name);}
(async()=>{
  await test('renter action emails owner with Polish summary and action link',async()=>{await queue(tx,incident,'opened','renter','opened:i','Problem przy odbiorze');await send('b');assert.equal(mails.length,1);assert.equal(mails[0].to,'owner@example.test');assert.match(mails[0].text,/Teraz Twoja kolej/);assert.match(mails[0].text,/https:\/\/staging.example.test\/account\/incidents\/b/);assert(mails[0].html.includes('&lt;script&gt;'));assert(!mails[0].html.includes('<script>'));});
  await test('owner proposal emails renter, rejection returns owner turn',async()=>{await queue(tx,{...incident,status:'AWAITING_RENTER',resolution:'Rabat',refundCents:4000},'proposed','owner','proposal:1');await queue(tx,{...incident,status:'ESCALATED'},'rejected','renter','reject:1');await send();assert.equal(mails[0].to,'renter@example.test');assert.match(mails[0].text,/40,00/);assert.equal(mails[1].to,'owner@example.test');assert.match(mails[1].text,/Teraz Twoja kolej/);});
  await test('each event supports notifications in both directions',async()=>{for(const event of ['opened','proposed','rejected','accepted','evidence','photos','escalated','retry'])for(const actor of ['owner','renter']){await queue(tx,incident,event,actor,`${event}:${actor}`,'Szczegóły');}assert.equal(rows.size,16);for(const row of rows.values())assert(row.to.endsWith('@example.test'));await send();await send();assert.equal(mails.length,16);for(const mail of mails){assert.match(mail.html,/Podsumowanie zgłoszenia/);assert.match(mail.html,/Następny krok/);assert.match(mail.html,/background:#111827/);assert.match(mail.html,/href="https:\/\/staging.example.test\/account\/incidents\/b"/);assert.match(mail.html,/Ta wiadomość została wysłana automatycznie/);}});
  await test('accepted agreement pending settlement does not announce completion',async()=>{await queue(tx,{...incident,status:'AGREEMENT_REACHED',acceptedAt:new Date(),resolution:'Uzgodniono',refundCents:1000},'accepted','renter','accept:i');await send();assert.equal(mails.length,1);assert.match(mails[0].text,/Rozliczenie Stripe jest w toku/);assert(!mails[0].subject.includes('zakończone'));});
  await test('bilaterally accepted completion emails both exactly once',async()=>{const resolved={...incident,status:'RESOLVED',acceptedAt:new Date(),resolution:'Akceptowany rabat',refundCents:5000};await queue(tx,resolved,'resolved',null,'resolved:i');await queue(tx,resolved,'resolved',null,'resolved:i');await Promise.all([send(),send()]);assert.equal(mails.length,2);assert.deepEqual(mails.map(m=>m.to).sort(),['owner@example.test','renter@example.test']);assert(mails.every(m=>m.text.includes('Akceptowany rabat')&&m.text.includes('50,00')&&m.text.includes('zaakceptowały obie strony')));await send();assert.equal(mails.length,2);});
  await test('no final email for unaccepted or still active decisions',async()=>{await queue(tx,{...incident,status:'RESOLVED'},'resolved',null,'resolved:i');await queue(tx,{...incident,status:'AGREEMENT_REACHED',acceptedAt:new Date()},'resolved',null,'resolved:i');assert.equal(rows.size,0);});
  await test('return completion records no rent refund and no damage arbitration',async()=>{await queue(tx,{...incident,stage:'RETURN',reason:'DAMAGED_ON_RETURN',status:'RESOLVED',acceptedAt:new Date(),resolution:'Wyjaśniono',refundCents:0},'resolved','owner','resolved:i');await send();assert.equal(mails.length,2);assert(mails.every(m=>m.text.includes('nie zmienia należnego wynagrodzenia')&&!m.text.includes('Uzgodniony zwrot najmu')));});
  await test('email snapshots retain original proposal when later proposals change',async()=>{await queue(tx,{...incident,resolution:'Pierwsza oferta',refundCents:1000},'proposed','owner','proposal:1');await queue(tx,{...incident,resolution:'Druga oferta',refundCents:2000},'proposed','owner','proposal:1');await send();assert.equal(mails.length,1);assert(mails[0].text.includes('Pierwsza oferta'));assert(!mails[0].text.includes('Druga oferta'));});
  await test('SMTP failure retries only the unsent email with backoff',async()=>{await queue(tx,{...incident,status:'RESOLVED',acceptedAt:new Date(),resolution:'Uzgodniono'},'resolved',null,'resolved:i');failTo='renter@example.test';await send();assert.equal(mails.length,1);const failed=Array.from(rows.values()).find(e=>!e.sentAt);assert(failed.nextAttemptAt>new Date());await send();assert.equal(mails.length,1);failed.nextAttemptAt=new Date(0);await send();assert.equal(mails.length,2);assert.equal(mails.filter(m=>m.to==='owner@example.test').length,1);});
  await test('application URL configured later is resolved before sending',async()=>{delete env.APP_URL;await queue(tx,incident,'opened','renter','opened:i');await send();assert.equal(mails.length,0);env.APP_URL='https://staging.example.test';for(const e of rows.values())e.nextAttemptAt=new Date(0);await send();assert.equal(mails.length,1);assert(mails[0].text.includes('https://staging.example.test/account/incidents/b'));assert(!mails[0].html.includes('__INCIDENT_URL__'));});
  await test('unrelated user cannot create notifications',async()=>{await assert.rejects(queue(tx,incident,'evidence','stranger','evidence:1'));assert.equal(rows.size,0);});

  await test('cancellation request emails owner with full refund proposal and claim link',async()=>{
    await queue(tx,{...incident,status:'AWAITING_OWNER',proposedById:'renter',resolution:'Prośba o anulowanie. Komentarz: uszkodzony przedmiot',refundCents:18000},'cancellation_requested','renter','cancel:1','uszkodzony przedmiot');
    await send(); assert.equal(mails.length,1); assert.equal(mails[0].to,'owner@example.test');
    assert.match(mails[0].subject,/Prośba o anulowanie/); assert.match(mails[0].text,/180,00/); assert.match(mails[0].text,/Teraz Twoja kolej/);
    assert(mails[0].html.includes("account/incidents/b")); assert.match(mails[0].text,/uszkodzony przedmiot/);
  });
  console.log(`${checks} incident email checks passed. No actual emails or database writes.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
