const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'..'),staged=root,ts=require(root+'/node_modules/typescript'),React=require(root+'/node_modules/react'),render=require(root+'/node_modules/react-dom/server').renderToStaticMarkup;
let role='ADMIN',userId='admin',calls=[],fail=false;const sample={charges:{data:[{id:'ch_test',created:1,currency:'pln',amount:22000,status:'succeeded',captured:true,refunded:false,amount_refunded:1500,payment_intent:'pi_test',metadata:{bookingId:'b'}}],has_more:true},refunds:{data:[{id:'re_test',created:2,currency:'pln',amount:1500,status:'succeeded',payment_intent:'pi_test',charge:'ch_test',metadata:{}}],has_more:false},transfers:{data:[{id:'tr_test',created:3,currency:'pln',amount:500,reversed:false,amount_reversed:0,destination:'acct_test',metadata:{bookingId:'b',type:'deposit_compensation'}}],has_more:false},balanceTransactions:{data:[{id:'txn_test',created:4,currency:'pln',amount:22000,fee:815,net:21185,status:'available',type:'charge',source:{id:'ch_test',payment_intent:'pi_test',metadata:{bookingId:'b'}}}],has_more:false}};
class StripeMock { constructor(){calls.push('constructor');this.balance={retrieve:async()=>{calls.push('balance');if(fail)throw Error('secret not for UI');return {livemode:false,available:[{currency:'pln',amount:10000}],pending:[{currency:'pln',amount:500}]};}} }
}
for(const k of Object.keys(sample))StripeMock.prototype[k]={list:async params=>{calls.push([k,params]);if(fail)throw Error('secret not for UI');return sample[k];}};
const prisma={user:{findUnique:async()=>({role})},booking:{findMany:async()=>[{id:'b',bookingNumber:10075,depositPaymentIntentId:'pi_test',depositChargeId:'ch_test',depositRefundId:'re_test',ownerTransferId:'tr_rent',depositTransferId:'tr_test',paymentRef:null}]}};
function load(f){const exports={};const text=fs.readFileSync(path.join(staged,f),'utf8');function req(id){if(id==='stripe')return {default:StripeMock,__esModule:true};if(id==='@/app/lib/auth')return {getSession:async()=>({user:{id:userId}})};if(id==='@/app/lib/prisma')return {prisma};if(id==='next/navigation')return {notFound:()=>{throw Error('notFound')},redirect:()=>{throw Error('redirect')}};if(id==='next/link')return {default:({children,href,prefetch,...rest})=>React.createElement('a',{href,...rest},children),__esModule:true};if(id.startsWith('@/'))return load(id.slice(2)+'.ts');return require(root+'/node_modules/'+id);}vm.runInNewContext(ts.transpileModule(text,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:req,Date,Intl,URLSearchParams,process:{env:{STRIPE_SECRET_KEY:'sk_test_mock'}}});return exports;}
(async()=>{const lib=load('app/lib/stripeFinance.ts');const stripe=new StripeMock();let rows=await lib.stripeFinanceRows(stripe,'payments',30,'ch_prev');assert.equal(rows.rows[0].returned,1500);assert.equal(rows.rows[0].status,'Częściowo zwrócona');assert.equal(calls.at(-1)[1].starting_after,'ch_prev');assert.equal(calls.at(-1)[1].limit,25);rows=await lib.stripeFinanceRows(stripe,'refunds',null);assert.equal(rows.rows[0].amount,1500);assert.equal(rows.rows[0].status,'Zwrócono');assert.equal(calls.at(-1)[1].created,undefined);rows=await lib.stripeFinanceRows(stripe,'transfers',7);assert.equal(rows.rows[0].destination,'acct_test');assert.equal(rows.rows[0].kind,'Kaucja — rekompensata');rows=await lib.stripeFinanceRows(stripe,'balance',90);assert.equal(rows.rows[0].fee,815);assert.equal(rows.rows[0].net,21185);assert.equal(rows.rows[0].bookingId,'b');assert.equal(lib.financeCursor('re_valid','payments'),undefined);assert.equal(lib.financeCursor('txn_valid','balance'),'txn_valid');assert.equal(lib.financeTab('nonsense'),'payments');assert.match(lib.currencyAmount(17500,'pln'),/175,00/);
const page=load('app/admin/finance/page.tsx').default;calls=[];role='USER';await assert.rejects(()=>page({searchParams:Promise.resolve({})}),/notFound/);assert.equal(calls.length,0);userId=null;await assert.rejects(()=>page({searchParams:Promise.resolve({})}),/redirect/);assert.equal(calls.length,0);userId='admin';role='ADMIN';for(const tab of ['payments','refunds','transfers','balance']){const html=render(await page({searchParams:Promise.resolve({tab})}));assert.match(html,/#10075/);assert.match(html,/sandbox/);assert.doesNotMatch(html,/sk_test_mock/);}fail=true;const html=render(await page({searchParams:Promise.resolve({})}));assert.match(html,/Nie udało się pobrać salda/);assert.match(html,/Nie udało się pobrać operacji/);assert.doesNotMatch(html,/secret not for UI/);console.log('Stripe adapter, four rendered tabs, admin authorization, pagination, metadata and failure handling verified with mocks. No Stripe requests made.');})().catch(e=>{console.error(e);process.exitCode=1;});
